# Auto-generated using compose2nix v0.2.1-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."nextjs-playground-main" = {
    image = "nextjs-playground";
    imageFile = pkgs.runCommand "nextjs-playground-main.tar.gz" {} ''
      ln -s ${./out/nextjs-playground.tar.gz} $out
    '';
    ports = [
      "3000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=main"
      "--network=nextjs-playground_default"
    ];
  };
  systemd.services."podman-nextjs-playground-main" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "no";
    };
    after = [
      "podman-network-nextjs-playground_default.service"
    ];
    requires = [
      "podman-network-nextjs-playground_default.service"
    ];
    partOf = [
      "podman-compose-nextjs-playground-root.target"
    ];
    wantedBy = [
      "podman-compose-nextjs-playground-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-nextjs-playground_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f nextjs-playground_default";
    };
    script = ''
      podman network inspect nextjs-playground_default || podman network create nextjs-playground_default
    '';
    partOf = [ "podman-compose-nextjs-playground-root.target" ];
    wantedBy = [ "podman-compose-nextjs-playground-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-nextjs-playground-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
