import { StrictMode } from "react";
import { Open_Sans } from "next/font/google";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: { default: "Demo", template: "%s | Demo App" },
  description: "Generated by demo app",
  applicationName: "Demo",
  authors: [
    { name: "KDevLab", url: "https://kdevlab.com" },
    { name: "Next.js Team", url: "https://nextjs.org" }
  ],
  generator: "KDevLab Engine",
};

const openSans = Open_Sans({ weight: "500", subsets: ["cyrillic", "cyrillic-ext", "latin", "latin-ext"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StrictMode>
      <html lang="en">
        <body className={openSans.className}>{children}</body>
      </html>
    </StrictMode>
  );
}
